---
apiVersion: bundle.dist.app/v1alpha1
kind: BundleConfig
metadata:
  name: default
spec:
  denoDeploy:
    entryPointUrl: mod.ts
    importMapUrl: import-map.json
    databases:
      default: ''
    requestTimeout: 5000

  appName: Login service
  appDesc: User authentication and profile management
  appIcon:
    type: glyph
    glyph:
      text: '👤'
      backgroundColor: 'rgb(51, 102, 51)'

# ---
# apiVersion: bundle.dist.app/v1alpha1
# kind: BundleMetadata
# metadata:
#   name: main
# spec:
#   appName: Login service
#   appDesc: User authentication and profile management
#   appIcon:
#     type: glyph
#     glyph:
#       text: 👤
#       backgroundColor: rgb(51, 102, 51)

# ---
# apiVersion: bundle.dist.app/v1alpha1
# kind: DenoDeploy
# metadata:
#   name: main
# spec:
#   entryPointUrl: mod.ts
#   attachDatabase: true
#   requestTimeout: 5000
